(() => {
  const canvas = document.querySelector('#world'), ctx = canvas.getContext('2d');
  const hotbarEl = document.querySelector('#hotbar'), inventoryEl = document.querySelector('#inventory'), inventoryGrid = document.querySelector('#inventory-grid');
  const timeLabel = document.querySelector('#time-label'), positionLabel = document.querySelector('#position-label'), toast = document.querySelector('#toast');
  const TILE = 32, WORLD_W = 600, WORLD_H = 70, DAY_LENGTH = 60;
  const types = [
    ['草方块','#668f4d','#97b65d'], ['泥土','#795d4d','#906c57'], ['石头','#68727b','#88949a'], ['深岩','#3e4650','#58616a'], ['木头','#896552','#b18461'], ['树叶','#3c8052','#58a568'], ['沙子','#c6ae72','#e0c98c'], ['玻璃','#93d5d7','#d0ffff'],
    ['砖块','#a4584f','#c87965'], ['木板','#aa7851','#cc9665'], ['白色羊毛','#d9dde0','#ffffff'], ['黑色羊毛','#303941','#4d5660'], ['红砖','#994439','#c95d48'], ['石砖','#77828a','#a6b1b2'], ['苔石','#557665','#76927a'], ['冰','#79c8dc','#c3f4ff'],
    ['水','#368ab0','#65c6dc'], ['熔岩','#bd542f','#ff9c35'], ['金矿','#8b7843','#e8c250'], ['铁矿','#5c6571','#d0a986'], ['煤矿','#44484b','#858381'], ['钻石矿','#367f8a','#8de4ea'], ['红石矿','#8b4147','#e98272'], ['书架','#865b43','#d5b15d'],
    ['玻璃板','#72aeb8','#b5e7e9'], ['灯笼','#b27535','#ffda73'], ['花盆','#a55b41','#cf8063'], ['花草','#468653','#e0a9d0'], ['工作台','#765d4e','#c49a65'], ['熔炉','#4a5159','#a0abb0'], ['箱子','#966338','#e2a75d'], ['紫水晶','#695591','#c9a9ee']
  ];
  let world, player, clouds, camera, keys = {}, selected = 0, zoom = 1, dayTime, last = 0, pointer = {x:0,y:0}, toastTimer;
  const rand = (a,b) => Math.floor(Math.random()*(b-a+1))+a;
  const clamp = (n,a,b) => Math.max(a, Math.min(b,n));
  function reset() { world = Array.from({length: WORLD_H}, () => Array(WORLD_W).fill(null)); let h = rand(27,35); for(let x=0;x<WORLD_W;x++){ h=clamp(h+rand(-1,1),22,39); for(let y=h;y<WORLD_H;y++) world[y][x] = y===h ? 0 : y<h+4 ? 1 : (Math.random()<.08?rand(2,3):2); if(Math.random()<.045 && h>23) makeTree(x,h); } player={x:Math.floor(WORLD_W/2)+.5,y:12,vx:0,vy:0,w:.68,h:1.75,onGround:false,crouch:false,sprint:false,hotbar:Array(8).fill(null)}; while(solid(Math.floor(player.x),Math.floor(player.y+player.h))) player.y--; camera={x:player.x,y:player.y}; clouds=Array.from({length:16},()=>({x:rand(-40,WORLD_W),y:rand(3,16),w:rand(3,7),speed:.006+Math.random()*.01})); dayTime=Math.random()*DAY_LENGTH; selected=0; zoom=1; fillHotbar(); notify('新的世界已生成'); }
  function makeTree(x,h){ if(x<2||x>WORLD_W-3)return; for(let y=h-1;y>h-5;y--) world[y][x]=4; for(let dx=-2;dx<=2;dx++) for(let dy=-2;dy<=1;dy++) if(Math.abs(dx)+Math.abs(dy)<4 && !world[h-5+dy]?.[x+dx]) world[h-5+dy][x+dx]=5; }
  const solid = (x,y) => x<0||x>=WORLD_W||y>=WORLD_H||(y>=0&&world[y][x]!==null&&world[y][x]!==16&&world[y][x]!==17);
  function resize(){const d=devicePixelRatio||1; canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0);} addEventListener('resize',resize); resize();
  function fillHotbar(){hotbarEl.innerHTML=''; for(let i=0;i<8;i++) hotbarEl.append(slot(i, player.hotbar[i], i)); }
  function slot(i,type,num){const b=document.createElement('button');b.className='slot'+(selected===i?' active':'');b.title=type===null?'空物品栏':types[type][0];b.dataset.name=type===null?'空物品栏':types[type][0]; if(type!==null){const c=document.createElement('canvas');c.width=c.height=32;drawMini(c.getContext('2d'),type);b.append(c)} b.insertAdjacentHTML('beforeend',`<span class="slot-number">${num+1}</span>`);b.onclick=()=>{selected=i;fillHotbar()};return b;}
  function drawMini(c,type){c.fillStyle=types[type][1];c.fillRect(2,2,28,28);c.fillStyle=types[type][2];c.fillRect(2,2,28,5); if(type===5){c.fillStyle='#337246';c.fillRect(5,10,6,6);c.fillRect(19,18,7,6)} if(type===6){c.fillStyle='#e7d49a';for(let i=0;i<7;i++)c.fillRect(6+i*4,8+(i%2)*8,2,2)} if(type===7){c.strokeStyle='rgba(255,255,255,.7)';c.strokeRect(3,3,26,26)} }
  function buildInventory(){ inventoryGrid.innerHTML=''; types.forEach((_,i)=>{const b=slot(i,i,i);b.onclick=()=>{player.hotbar[selected]=i;fillHotbar();notify(`${types[i][0]} 已放入当前槽位`)};inventoryGrid.append(b)}); }
  function openBag(show){inventoryEl.hidden=!show;if(show)buildInventory()}
  function notify(text){toast.textContent=text;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1800)}
  function resizeWorld(){const w=innerWidth,h=innerHeight; camera.x += (player.x-camera.x)*.12; camera.y += (player.y-camera.y)*.12; const viewW=w/(TILE*zoom), viewH=h/(TILE*zoom); return {w,h,viewW,viewH,left:camera.x-viewW/2,top:camera.y-viewH/2};}
  function draw(){const v=resizeWorld(); let t=(Math.sin(dayTime/DAY_LENGTH*Math.PI*2)+1)/2; const sky=`rgb(${Math.round(26+83*t)},${Math.round(42+147*t)},${Math.round(70+169*t)})`;ctx.fillStyle=sky;ctx.fillRect(0,0,v.w,v.h); drawSky(v,t); const sx=TILE*zoom; for(let y=Math.max(0,Math.floor(v.top)-1);y<Math.min(WORLD_H,Math.ceil(v.top+v.viewH)+1);y++) for(let x=Math.max(0,Math.floor(v.left)-1);x<Math.min(WORLD_W,Math.ceil(v.left+v.viewW)+1);x++){let type=world[y][x];if(type!==null)drawBlock(x,y,type,v,sx)} drawPlayer(v,sx); let darkness=clamp(.52-t*.64,0,.5);ctx.fillStyle=`rgba(10,18,42,${darkness})`;ctx.fillRect(0,0,v.w,v.h); updateHud();}
  function drawSky(v,t){ctx.save();const sx=TILE*zoom;ctx.globalAlpha=.7;clouds.forEach(c=>{c.x+=c.speed;if(c.x>WORLD_W+10)c.x=-15;ctx.fillStyle=t>.35?'#fff':'#b8c8dd';const x=(c.x-v.left)*sx,y=(c.y-v.top)*sx;ctx.beginPath();ctx.arc(x,y,12*zoom,0,7);ctx.arc(x+16*zoom,y-8*zoom,16*zoom,0,7);ctx.arc(x+35*zoom,y,12*zoom,0,7);ctx.fill();});ctx.globalAlpha=1;const phase=dayTime/DAY_LENGTH;const isDay=phase<.5;const arcPhase=isDay?phase*2:phase*2-1;const ang=Math.PI*arcPhase;const celestialX=v.w/2+Math.cos(ang)*v.w*.38,celestialY=v.h*.72-Math.sin(ang)*v.h*.52;if(isDay){ctx.fillStyle='#ffe16a';ctx.beginPath();ctx.arc(celestialX,celestialY,22*zoom,0,7);ctx.fill();}else{const moonPhase=Math.floor((phase-.5)*16)%8;ctx.fillStyle='#f3f0cf';ctx.beginPath();ctx.arc(celestialX,celestialY,19*zoom,0,7);ctx.fill();ctx.fillStyle='#a6b4ca';ctx.beginPath();ctx.arc(celestialX+(moonPhase-3)*5*zoom,celestialY,19*zoom,0,7);ctx.fill();}ctx.restore();}
  function drawBlock(x,y,type,v,sx){const px=(x-v.left)*sx,py=(y-v.top)*sx;ctx.fillStyle=types[type][1];ctx.fillRect(px,py,sx+1,sx+1);ctx.fillStyle=types[type][2];ctx.fillRect(px,py,sx+1,Math.max(2,sx*.12));ctx.strokeStyle='rgba(28,39,43,.2)';ctx.strokeRect(px+.5,py+.5,sx-1,sx-1);if(type===4){ctx.fillStyle='#5e422f';ctx.fillRect(px+sx*.4,py+sx*.15,sx*.2,sx*.7)}if(type===5){ctx.fillStyle='rgba(22,75,45,.35)';ctx.fillRect(px+sx*.2,py+sx*.35,sx*.18,sx*.18);ctx.fillRect(px+sx*.65,py+sx*.7,sx*.16,sx*.16)}if(type===16){ctx.fillStyle='rgba(180,240,255,.35)';ctx.fillRect(px,py,sx,sx)}}
  function drawPlayer(v,sx){const x=(player.x-player.w/2-v.left)*sx,w=player.w*sx,visualH=player.crouch?1.35:1.75,h=visualH*sx,y=(player.y+player.h-visualH-v.top)*sx;ctx.save();ctx.lineWidth=Math.max(1,zoom);if(player.crouch){ctx.fillStyle='#2e3441';ctx.fillRect(x+w*.12,y,w*.72,h*.2);ctx.fillStyle='#e0a47e';ctx.fillRect(x+w*.28,y+h*.2,w*.5,h*.22);ctx.fillStyle='#3e7895';ctx.fillRect(x+w*.16,y+h*.42,w*.72,h*.3);ctx.fillStyle='#e8d9b5';ctx.fillRect(x+w*.42,y+h*.27,w*.09,h*.08);ctx.fillStyle='#263342';ctx.fillRect(x+w*.18,y+h*.72,w*.27,h*.28);ctx.fillRect(x+w*.56,y+h*.72,w*.27,h*.28);}else{ctx.fillStyle='#2e3441';ctx.fillRect(x+w*.16,y,w*.68,h*.2);ctx.fillStyle='#e0a47e';ctx.fillRect(x+w*.22,y+h*.2,w*.56,h*.21);ctx.fillStyle='#202a36';ctx.fillRect(x+w*.3,y+h*.3,w*.08,h*.06);ctx.fillRect(x+w*.62,y+h*.3,w*.08,h*.06);ctx.fillStyle='#3e7895';ctx.fillRect(x+w*.16,y+h*.41,w*.68,h*.34);ctx.fillStyle='#e8d9b5';ctx.fillRect(x+w*.28,y+h*.47,w*.1,h*.08);ctx.fillStyle='#263342';ctx.fillRect(x+w*.18,y+h*.72,w*.28,h*.28);ctx.fillRect(x+w*.54,y+h*.72,w*.28,h*.28);ctx.fillStyle='#b55e4d';ctx.fillRect(x+w*.17,y+h*.42,w*.68,h*.06);}ctx.restore();}
  function updateHud(){const phase=dayTime/DAY_LENGTH;timeLabel.textContent=phase<.46?'白昼':phase<.56?'黄昏':'夜晚';positionLabel.textContent=`坐标 ${Math.floor(player.x)}, ${Math.floor(player.y)}`;}
  function canMove(x,y){const left=Math.floor(x-player.w/2),right=Math.floor(x+player.w/2-.001),top=Math.floor(y),bottom=Math.floor(y+player.h-.001);for(let ty=top;ty<=bottom;ty++)for(let tx=left;tx<=right;tx++)if(solid(tx,ty))return false;return true;}
  function moveHorizontal(distance){const steps=Math.max(1,Math.ceil(Math.abs(distance)/.08)),step=distance/steps;for(let i=0;i<steps;i++){if(canMove(player.x+step,player.y)){player.x+=step;continue}const dir=Math.sign(step);if(player.onGround&&dir&&canMove(player.x+dir*.08,player.y-1)){player.vy=-8.2;player.onGround=false;}break;}}
  function moveVertical(distance){const steps=Math.max(1,Math.ceil(Math.abs(distance)/.08)),step=distance/steps;for(let i=0;i<steps;i++){if(canMove(player.x,player.y+step)){player.y+=step;player.onGround=false;continue}if(step>0)player.onGround=true;player.vy=0;break;}}
  function physics(dt){const moving=keys.a||keys.d||keys.ArrowLeft||keys.ArrowRight;if(!moving)player.sprint=false;const run=player.sprint?1.65:1,crouch=keys.Shift;player.crouch=crouch;const speed=(crouch?2.1:4.2)*run;player.vx=((keys.a||keys.ArrowLeft)?-speed:0)+((keys.d||keys.ArrowRight)?speed:0);if((keys.w||keys.ArrowUp||keys[' '])&&player.onGround){player.vy=-8.2;player.onGround=false;keys[' ']=false;}player.vy+=20*dt;moveHorizontal(player.vx*dt);moveVertical(player.vy*dt);if(player.y>WORLD_H)reset();dayTime=(dayTime+dt)%DAY_LENGTH;}
  function target(){const v=resizeWorld(),sx=TILE*zoom;return {x:Math.floor(v.left+pointer.x/sx),y:Math.floor(v.top+pointer.y/sx),v};}
  function inReach(x,y){return Math.hypot(x+.5-player.x,y+.5-(player.y+player.h/2))<5.5;}
  function overlapsPlayer(x,y){return x<player.x+player.w/2&&x+1>player.x-player.w/2&&y<player.y+player.h&&y+1>player.y;}
  function action(button){const q=target();if(!inReach(q.x,q.y)){notify('距离太远');return}if(q.x<0||q.x>=WORLD_W||q.y<0||q.y>=WORLD_H)return;if(button===0){if(world[q.y][q.x]!==null){world[q.y][q.x]=null;notify('方块已破坏')}}else{if(world[q.y][q.x]===28){notify('工作台：可以合成物品');return}const type=player.hotbar[selected];if(type==null){notify('物品栏为空，按 B 打开背包');return}if(world[q.y][q.x]===null){if(overlapsPlayer(q.x,q.y)){notify('这里会和人物重叠');return}world[q.y][q.x]=type;notify(`${types[type][0]} 已放置`)}}}
  canvas.addEventListener('mousemove',e=>{pointer.x=e.clientX;pointer.y=e.clientY});canvas.addEventListener('mousedown',e=>{if(!inventoryEl.hidden)return;e.preventDefault();if(e.target===canvas)action(e.button)});canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{zoom=clamp(zoom+(e.deltaY<0?.1:-.1),.2,2);notify(`视野 ${Math.round(zoom*100)}%`)},{passive:true});
  addEventListener('keydown',e=>{keys[e.key]=true;keys[e.key.toLowerCase()]=true;if(e.key==='Control')player.sprint=true;if(e.key.toLowerCase()==='b'){openBag(inventoryEl.hidden);e.preventDefault()}if(e.key>='1'&&e.key<='8'){selected=+e.key-1;fillHotbar()}if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault()});addEventListener('keyup',e=>{keys[e.key]=false;keys[e.key.toLowerCase()]=false;if(e.key==='Shift')player.crouch=false});
  document.querySelector('#help-toggle').onclick=()=>document.querySelector('#help-panel').classList.toggle('is-hidden');document.querySelector('#reset-btn').onclick=()=>{if(confirm('确定要重置当前世界吗？'))reset()};document.querySelector('#close-inventory').onclick=()=>openBag(false);
  hotbarEl.addEventListener('contextmenu',e=>{const button=e.target.closest('.slot');if(!button)return;e.preventDefault();const index=[...hotbarEl.children].indexOf(button);if(index>=0)player.hotbar[index]=null;fillHotbar();});
  function loop(now){const dt=Math.min((now-last)/1000||0,.05);last=now;physics(dt);draw();requestAnimationFrame(loop)}
  reset(); requestAnimationFrame(loop);
})();
